"""Add max/limit per day column to EntryType table.

Revision ID: 1f0753ea2be6
Revises: 7cc1a275653b
Create Date: 2026-07-31 11:42:40.052502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0753ea2be6'
down_revision = '7cc1a275653b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_types') as batch_op:
        batch_op.add_column(sa.Column('max_per_day', sa.Integer(), nullable=True))
    
    # 2. Populate the table data
    op.execute(
        sa.text("""
            UPDATE entry_types SET max_per_day = 3
        """)
    )
    
    # 3. Alter the column to NOT NULL using batch mode
    with op.batch_alter_table('entry_types') as batch_op:
        batch_op.alter_column('max_per_day', nullable=False, existing_type=sa.Integer())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_types', schema=None) as batch_op:
        batch_op.drop_column('max_per_day')

    # ### end Alembic commands ###
