"""Rename outfits to entries

Revision ID: 7cc1a275653b
Revises: 8321e682335d
Create Date: 2026-07-22 11:54:25.831668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc1a275653b'
down_revision = '8321e682335d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("outfits", "entries")


    op.create_table('entry_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    connection = op.get_bind()

    connection.execute(
        sa.text("""
            INSERT INTO entry_types (name, created_at)
            VALUES ('Outfit', CURRENT_TIMESTAMP)
        """)
    )

    with op.batch_alter_table("entries") as batch_op:
        batch_op.add_column(sa.Column("type_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("entry_date", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("name", sa.String(255), nullable=True))

    connection.execute(
        sa.text("""
            UPDATE entries
            SET name = 'Imported Outfit'
        """)
    )

    connection.execute(
        sa.text("""
            UPDATE entries
            SET entry_date = created_at
        """)
    )

    connection.execute(
        sa.text("""
            UPDATE entries
            SET created_at = CURRENT_TIMESTAMP
        """)
    )

    result = connection.execute(
        sa.text("""
            SELECT id
            FROM entry_types
            WHERE name='Outfit'
        """)
    )

    type_id = result.fetchone()[0]

    connection.execute(
        sa.text("""
            UPDATE entries
            SET type_id = :type_id
        """),
        {"type_id": type_id}
    )

    with op.batch_alter_table("entries") as batch_op:

        batch_op.alter_column("type_id", nullable=False)

        batch_op.alter_column("entry_date", nullable=False)

        batch_op.alter_column("name", nullable=False)

        batch_op.create_foreign_key(
            "fk_entries_type_id",
            "entry_types",
            ["type_id"],
            ["id"]
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('outfits',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('description', sa.TEXT(), nullable=True),
    # sa.Column('icon', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_outfits_user_id_users')),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('entries')
    # op.drop_table('entry_types')
    raise NotImplementedError("Downgrade not supported for this migration.")
    # ### end Alembic commands ###
