"""Add users

Revision ID: 8321e682335d
Revises: 
Create Date: 2026-06-30 12:28:33.713516

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash

# revision identifiers, used by Alembic.
revision = '8321e682335d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    connection = op.get_bind()

    hashed_password = generate_password_hash("password")

    connection.execute(
        sa.text("""
            INSERT INTO users (username, email, password_hash, created_at)
            VALUES (:username, :email, :password_hash, CURRENT_TIMESTAMP)
        """),
        {
            "username": "bhoff",
            "email": "bhoff@ucmerced.edu",
            "password_hash": hashed_password
        }
    )

    user_id = 1

    connection.execute(
        sa.text("UPDATE outfits SET user_id = :user_id"),
        {"user_id": user_id}
    )

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key("fk_outfits_user_id_users", 'users', ['user_id'], ['id'])
        batch_op.drop_column('entry_date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint("fk_outfits_user_id_users", type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
